//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QiuYudengMathematics.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BulletinBoard
    {
        public BulletinBoard()
        {
            this.BoardComment = new HashSet<BoardComment>();
        }
    
        public int BulletinBoardSeq { get; set; }
        public string Content { get; set; }
        public int SubjectId { get; set; }
        public bool Enable { get; set; }
    
        public virtual ICollection<BoardComment> BoardComment { get; set; }
        public virtual GroupGradeSubject GroupGradeSubject { get; set; }
    }
}
