//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QiuYudengMathematics.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupGradeSubject
    {
        public GroupGradeSubject()
        {
            this.Student = new HashSet<Student>();
            this.BulletinBoard = new HashSet<BulletinBoard>();
            this.CourseVideo = new HashSet<CourseVideo>();
        }
    
        public int ID { get; set; }
        public int GradeID { get; set; }
        public string Subject { get; set; }
        public bool Enable { get; set; }
    
        public virtual GroupGrade GroupGrade { get; set; }
        public virtual ICollection<Student> Student { get; set; }
        public virtual ICollection<BulletinBoard> BulletinBoard { get; set; }
        public virtual ICollection<CourseVideo> CourseVideo { get; set; }
    }
}
